/*
 * build-panel.mjs — regenerate Coverage Bench's PANEL array.
 *
 *   node build-panel.mjs
 *
 * Reads the sourced product records out of index.html (Policy Desk) and merges
 * them with the bench-only fields in bench-data.json, then writes the result
 * into coverage-bench.html between the PANEL:BEGIN / PANEL:END markers.
 *
 * The point of the split: index.html is the one place the sourced facts live,
 * bench-data.json is the one place the estimates live, and neither artifact can
 * quietly drift away from the other. Both published pages stay standalone —
 * this script is a regeneration tool, not a runtime dependency.
 */
import { readFileSync, writeFileSync } from "node:fs";

const PRODUCTS_SRC = "index.html";
const BENCH_SRC = "bench-data.json";
const TARGET = "coverage-bench.html";
const BEGIN = "/* PANEL:BEGIN — generated by build-panel.mjs, do not edit by hand */";
const END = "/* PANEL:END */";

/* ── pull the PRODUCTS literal out of index.html without running the app ── */
function readProducts(file) {
  const src = readFileSync(file, "utf8");
  const at = src.indexOf("const PRODUCTS = [");
  if (at < 0) throw new Error(`PRODUCTS array not found in ${file}`);
  const open = src.indexOf("[", at);

  let depth = 0, close = -1, inStr = null, esc = false;
  for (let i = open; i < src.length; i++) {
    const c = src[i];
    if (inStr) {
      if (esc) { esc = false; continue; }
      if (c === "\\") { esc = true; continue; }
      if (c === inStr) inStr = null;
      continue;
    }
    if (c === '"' || c === "'" || c === "`") { inStr = c; continue; }
    if (c === "/" && src[i + 1] === "*") { i = src.indexOf("*/", i) + 1; continue; }
    if (c === "/" && src[i + 1] === "/") { i = src.indexOf("\n", i); continue; }
    if (c === "[") depth++;
    else if (c === "]" && --depth === 0) { close = i; break; }
  }
  if (close < 0) throw new Error("unbalanced PRODUCTS array");
  return new Function("return " + src.slice(open, close + 1))();
}

/* ── which bench fields each family can estimate ────────────────────────── */
function estimable(family, row) {
  const keys = ["prem"];
  if (family === "hospital") {
    if (row.attachesTo) keys.push("coins", "cap");
    else keys.push("ward", "limit", "deductible", "coins");
    if (row.rider) keys.push("rider", "riderPrem");
    if (row.benefitLimit !== undefined) keys.push("benefitLimit");
  } else if (family === "lumpsum") {
    keys.push("payout");
    if (row.ciTotal !== undefined) keys.push("ciTotal");
    if (row.monthly !== undefined || row.pctOfIncome !== undefined) keys.push("monthly");
  } else if (family === "accumulation") {
    keys.push("premYears", "illusLow", "illusHigh");
  } else if (family === "general") {
    keys.push("benefitLimit");
  }
  return keys;
}

/* ── merge one panel record + one bench row into a bench product ────────── */
function merge(panel, bench, row, tierKey) {
  const family = bench.family;
  const sourced = new Set([...(bench.sourced || []), ...(row.sourced || [])]);
  if (sourced.has("prem")) {
    throw new Error(`${panel.id}: premium curves are never sourced — remove "prem" from its sourced list`);
  }

  /* estimates = the bench fields this family can estimate, minus whatever was
     actually sourced, plus whatever the panel record already flagged itself. */
  const est = estimable(family, row).filter((k) => !sourced.has(k));
  for (const k of panel.est || []) if (!est.includes(k)) est.push(k);

  const out = {
    id: tierKey ? `${panel.id}#${tierKey}` : panel.id,
    panelId: panel.id,
    name: row.name || panel.name,
    insurer: panel.insurer,
    family,
    category: panel.category,
    type: panel.type,
    needs: panel.needs || [],
    premiumBasis: panel.premiumBasis,
    coverageTerm: panel.coverageTerm,
    entryAge: panel.entryAge,
    sumAssured: panel.sumAssured,
    uw: panel.uw,
    status: panel.status,
    summary: panel.summary,
    notes: panel.notes || [],
    source: panel.source,
    sourceName: panel.sourceName,
    sourced: panel.sourced,
    est,
    prem: row.prem,
  };
  if (panel.statusNote) out.statusNote = panel.statusNote;

  const note = row === bench ? bench.tierNote : [row.tierNote, bench.tierNote].filter(Boolean).join(" ");
  if (note) out.note = note;

  /* family-specific engine numbers, copied only when the family uses them */
  const carry = {
    hospital: ["ward", "limit", "deductible", "coins", "rider", "riderPrem", "attachesTo", "cap", "benefitLimit"],
    lumpsum: ["payout", "ciTotal", "benefitKind", "monthly", "pctOfIncome"],
    accumulation: ["horizon"],
    general: ["benefitLimit"],
  }[family];
  for (const k of carry) if (row[k] !== undefined) out[k] = row[k];

  return out;
}

/* ── build ──────────────────────────────────────────────────────────────── */
const products = readProducts(PRODUCTS_SRC);
const bench = JSON.parse(readFileSync(BENCH_SRC, "utf8"));

const missing = products.filter((p) => !bench[p.id]).map((p) => p.id);
if (missing.length) throw new Error(`no bench data for: ${missing.join(", ")}`);
const orphan = Object.keys(bench).filter((id) => !products.some((p) => p.id === id));
if (orphan.length) throw new Error(`bench data for products not on the panel: ${orphan.join(", ")}`);

const panel = [];
for (const p of products) {
  const b = bench[p.id];
  if (b.tiers) for (const t of b.tiers) panel.push(merge(p, b, t, t.key));
  else panel.push(merge(p, b, b, null));
}

const seen = new Set();
for (const r of panel) {
  if (seen.has(r.id)) throw new Error(`duplicate bench id: ${r.id}`);
  seen.add(r.id);
  if (!r.source) throw new Error(`${r.id}: no source link`);
  const ages = Object.keys(r.prem || {});
  if (ages.length !== 7) throw new Error(`${r.id}: premium curve needs 7 anchors, has ${ages.length}`);
}

/* A client need that only one family can answer must not pick up members from
   another — that is how a savings plan ends up filed under a protection need,
   or a travel policy under hospital bills. Warn rather than throw: an adviser
   may legitimately add a need that spans families (Legacy planning does). */
const NEED_FAMILY = {
  "Hospital bills": "hospital",
  "Cancer drug costs": "hospital",
  "Overseas medical": "general",
  "Travel disruption": "general",
  "Domestic helper": "general",
  "Accident cover": "lumpsum",
  "Income replacement": "lumpsum",
  "Mortgage protection": "lumpsum",
  "Critical illness cover": "lumpsum",
  "Retirement income": "accumulation",
  "Child education": "accumulation",
};
for (const [need, want] of Object.entries(NEED_FAMILY)) {
  const strays = panel.filter((r) => r.needs.includes(need) && r.family !== want);
  for (const r of strays) {
    console.warn(`  ! "${r.name}" is ${r.family}, but carries the ${want}-only need "${need}"`);
  }
}

const body = panel.map((r) => JSON.stringify(r)).join(",\n");
const block = `${BEGIN}\nvar PANEL = [\n${body}\n];\n${END}`;

let html = readFileSync(TARGET, "utf8");
const from = html.indexOf(BEGIN);
const to = html.indexOf(END);
if (from < 0 || to < 0) throw new Error(`${TARGET} has no PANEL:BEGIN / PANEL:END markers`);
html = html.slice(0, from) + block + html.slice(to + END.length);
writeFileSync(TARGET, html);

const byFamily = panel.reduce((a, r) => ((a[r.family] = (a[r.family] || 0) + 1), a), {});
console.log(
  `${products.length} panel products → ${panel.length} bench lines ` +
    `(${Object.entries(byFamily).map(([k, n]) => `${k} ${n}`).join(", ")})`
);
